<?php
/**
 * Created by PhpStorm.
 * User: julien
 * Date: 25.07.18
 * Time: 21:04
 */

/**
 * Implements hook_menu().
 */
function babylon_menu()
{
    $items = array();

    $items['babylon'] = array(
        'title' => 'Babylon',
        'page callback' => 'babylon_create_3d',
        'access callback' => TRUE,

    );

    return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function babylon_preprocess_page(&$variables)
{
    drupal_add_js(drupal_get_path('module', 'babylon') . '/js/babylon_test.js', array('scope' => 'footer', 'weight' => 4));
    drupal_add_js('https://cdn.babylonjs.com/babylon.js', 'external');
    drupal_add_js('https://preview.babylonjs.com/loaders/babylonjs.loaders.min.js', 'external');
}

function babylon_create_3d() {

    //drupal_add_js(drupal_get_path('module', 'babylon') . '/js/babylon_test.js');
    drupal_add_css(drupal_get_path('module', 'babylon') . '/js/babylon.css');

    $canvas = array(
        '#prefix' => '<canvas id="renderCanvas" touch-action="none">',
        '#suffix' => '</canvas>',
    );

    return $canvas;
}